Repository Robert-Fairley/apple-news-client, pull requests merged in 2019-10, with the labels that each got.

#8 ability to search with parameters
  src/index.ts
Labels: enhancement

#9 [ Patch ] Update dependencies.
  package-lock.json
  package.json
Labels: bug, dependencies

#10 2 minor bug fixes
  README.md
  src/index.ts
Labels: bug, enhancement

#14 Enabling named export alongside default one
  README.md
  index.js
  src/index.ts
Labels: bug, documentation, enhancement

#15 Promises support, readme to include searchArticles
  README.md
  src/index.ts
Labels: documentation, enhancement
